import javax.swing.*;
import java.awt.Font;
import java.awt.event.ActionEvent;

public class GameOverWindow extends JPanel {

    public GameOverWindow(int n, String s1, String s2) {
        initComponents(n, s1, s2);
    }

    private void initComponents(int n, String s1, String s2) {
        JPanel panel = new JPanel();
        JLabel lTitle = new JLabel();
        JLabel lResult1 = new JLabel();
        JLabel lResult2 = new JLabel();
        JLabel lTeam = new JLabel();
        JButton bBackToMain = new JButton();

        panel.setBackground(View.PRIMARY_COLOR);
        panel.setForeground(View.SECONDARY_COLOR);

        lTitle.setFont(new Font("Segoe UI", Font.BOLD, 60)); // NOI18N
        lTitle.setForeground(View.SECONDARY_COLOR);
        lTitle.setHorizontalAlignment(SwingConstants.CENTER);
        switch (n) {
            case 0 -> lTitle.setText("<html><center>GAME OVER<br><br>A szerelők győztek</html>");
            case 1 -> lTitle.setText("<html><center>GAME OVER<br><br>A szabotőrök győztek</html>");
            case 2 -> lTitle.setText("<html><center>GAME OVER<br><br>Döntetlen</html>");
        }

        lResult1.setFont(new Font("Segoe UI", Font.BOLD, 35)); // NOI18N
        lResult1.setForeground(View.SECONDARY_COLOR);
        lResult1.setHorizontalAlignment(SwingConstants.CENTER);
        lResult1.setText(s1);

        lResult2.setFont(new Font("Segoe UI", Font.BOLD, 35)); // NOI18N
        lResult2.setForeground(View.SECONDARY_COLOR);
        lResult2.setHorizontalAlignment(SwingConstants.CENTER);
        lResult2.setText(s2);

        lTeam.setFont(new Font("Segoe UI Semibold", Font.ITALIC, 18)); // NOI18N
        lTeam.setForeground(View.SECONDARY_COLOR);
        lTeam.setHorizontalAlignment(SwingConstants.CENTER);
        lTeam.setText("macisajt csapat");

        bBackToMain.setBackground(View.SECONDARY_COLOR);
        bBackToMain.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 36)); // NOI18N
        bBackToMain.setForeground(View.PRIMARY_COLOR);
        bBackToMain.setText("VISSZA A FŐMENÜBE");
        bBackToMain.addActionListener(this::bBackToMainActionPerformed);


        // Generated by NetBeans
        GroupLayout jPanel2Layout = new GroupLayout(panel);
        panel.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(lTitle, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lTeam, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lResult1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lResult2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(273, 273, 273)
                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(bBackToMain, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(274, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(lTitle)
                                .addGap(40, 40, 40)
                                .addComponent(lResult1)
                                .addComponent(lResult2)
                                .addGap(18, 18, 18)
                                .addComponent(bBackToMain, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                                .addComponent(lTeam, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE))
        );
        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(panel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(panel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        // End of generated code
    }

    private void bBackToMainActionPerformed(ActionEvent evt) {
        View.setContentPane(new MainMenuWindow());
    }
}
