import javax.swing.*;
import java.awt.*;

public class MainMenuWindow extends JPanel {

    public MainMenuWindow() {
        initComponents();
    }

    private void initComponents() {
        JPanel panel = new JPanel();
        JLabel lTitle = new JLabel();
        JLabel lTeam = new JLabel();
        JButton bNewGame = new JButton();
        JButton bLoadGame = new JButton();
        JButton bExitGame = new JButton();

        panel.setBackground(View.SIENNA);
        panel.setForeground(View.MOCCASIN);

        lTitle.setFont(new java.awt.Font("Segoe UI", Font.BOLD, 60)); // NOI18N
        lTitle.setForeground(View.MOCCASIN);
        lTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitle.setText("SIVATAGI VÍZHÁLÓZAT");

        lTeam.setFont(new java.awt.Font("Segoe UI Semibold", Font.ITALIC, 18)); // NOI18N
        lTeam.setForeground(View.MOCCASIN);
        lTeam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTeam.setText("macisajt csapat");

        bNewGame.setBackground(View.MOCCASIN);
        bNewGame.setFont(new java.awt.Font("Segoe UI Semibold", Font.PLAIN, 36)); // NOI18N
        bNewGame.setForeground(View.SIENNA);
        bNewGame.setText("ÚJ JÁTÉK INDÍTÁSA");
        bNewGame.addActionListener(this::bNewGameActionPerformed);

        bLoadGame.setBackground(View.MOCCASIN);
        bLoadGame.setFont(new java.awt.Font("Segoe UI Semibold", Font.PLAIN, 36)); // NOI18N
        bLoadGame.setForeground(View.SIENNA);
        bLoadGame.setText("KORÁBBI JÁTÉK BETÖLTÉSE");
        bLoadGame.addActionListener(this::bLoadGameActionPerformed);

        bExitGame.setBackground(View.MOCCASIN);
        bExitGame.setFont(new java.awt.Font("Segoe UI Semibold", Font.PLAIN, 36)); // NOI18N
        bExitGame.setForeground(View.SIENNA);
        bExitGame.setText("KILÉPÉS A PROGRAMBÓL");
        bExitGame.addActionListener(this::bExitGameActionPerformed);

        // Generated by NetBeans
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(panel);
        panel.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lTeam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(273, 273, 273)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(bExitGame, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                                        .addComponent(bLoadGame, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                                        .addComponent(bNewGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(274, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(lTitle)
                                .addGap(103, 103, 103)
                                .addComponent(bNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(bLoadGame, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(bExitGame, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                                .addComponent(lTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        // End of generated code
    }

    private void bNewGameActionPerformed(java.awt.event.ActionEvent evt) {
        View.FRAME.setContentPane(new NewGameWindow());
        View.FRAME.invalidate();
        View.FRAME.validate();
        View.FRAME.repaint();
    }

    private void bLoadGameActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO: korábbi játék betöltése gomb
    }

    private void bExitGameActionPerformed(java.awt.event.ActionEvent evt) {
        View.FRAME.dispose();
    }
}
